# <center>Assignment 2
Deadline 7.02.2021 23:59

Name:
ID:


# Part 1

**In part 1 you need to work with data from the about 120 years of Olympic history by pandas. Write code and perform computations in the cells below. There are five questions.** 

Download the file `athlete_events.csv` from [here](https://drive.google.com/file/d/1f5v6Z2ayc7h698FG_98wP5x1Y2zZQeox/view?usp=sharing). The dataset has the following features:

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [1]:
import pandas as pd

In [2]:
PATH = 'athlete_events.csv'

In [3]:
data = pd.read_csv(PATH)
data.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

__1. How old were the oldest male and female participants of the 2012 Olympics?__

In [4]:
a1 = data.sort_values(by=['Age', 'Sex'], ascending=[False, True])
a1.head(1)

ID                    Name Sex   Age  Height  Weight  \
257054  128719  John Quincy Adams Ward   M  97.0     NaN     NaN   

                 Team  NOC        Games  Year  Season       City  \
257054  United States  USA  1928 Summer  1928  Summer  Amsterdam   

                   Sport                                        Event Medal  
257054  Art Competitions  Art Competitions Mixed Sculpturing, Statues   NaN

In [5]:
a2 = data.sort_values(by=['Sex', 'Age'], ascending=[True, False])
a2.head(1)

ID                                    Name Sex   Age  Height  \
201631  101272  Ernestine Lonie Ernesta Robert-Mrignac   F  74.0     NaN   

        Weight    Team  NOC        Games  Year  Season   City  \
201631     NaN  France  FRA  1924 Summer  1924  Summer  Paris   

                   Sport                               Event Medal  
201631  Art Competitions  Art Competitions Mixed Sculpturing   NaN

In [6]:
a2['Age'][201631]

74.0

In [7]:
# ANSWER: Male - 97 and Female - 74

__2. What are the mean and standard deviation of height for male basketball players who participated in the 1992 Olympics? Round the answer to the first decimal.__

In [8]:
import statistics as st

In [10]:
df = data.groupby(['Year'])
df2 = df.get_group(1992)
df3 = df2.groupby(['Sex'])
df4 = df3.get_group('M')
df4.head()

ID             Name Sex   Age  Height  Weight           Team  NOC  \
0    1        A Dijiang   M  24.0   180.0    80.0          China  CHN   
10   6  Per Knut Aaland   M  31.0   188.0    75.0  United States  USA   
11   6  Per Knut Aaland   M  31.0   188.0    75.0  United States  USA   
12   6  Per Knut Aaland   M  31.0   188.0    75.0  United States  USA   
13   6  Per Knut Aaland   M  31.0   188.0    75.0  United States  USA   

          Games  Year  Season         City                 Sport  \
0   1992 Summer  1992  Summer    Barcelona            Basketball   
10  1992 Winter  1992  Winter  Albertville  Cross Country Skiing   
11  1992 Winter  1992  Winter  Albertville  Cross Country Skiing   
12  1992 Winter  1992  Winter  Albertville  Cross Country Skiing   
13  1992 Winter  1992  Winter  Albertville  Cross Country Skiing   

                                                Event Medal  
0                         Basketball Men's Basketball   NaN  
10           Cross Country Skiing Men's 10 kilometres   NaN  
11           Cross Country Skiing Men's 50 kilometres   NaN  
12  Cross Country Skiing Men's 10/15 kilometres Pu...   NaN  
13  Cross Country Skiing Men's 4 x 10 kilometres R...   NaN

In [11]:
height_list = []
for i in df4['Height']:
    if i > 1:
        height_list.append(i)

In [12]:
round(st.mean(height_list), 1)

179.7

In [13]:
round(st.stdev(height_list), 1)

9.5

In [14]:
# ANSWER: Mean: 179.7 and Standard devision: 9.5

__3. How many times did Christine Jacoba Aaftink participate in the Olympics held in different years?__

In [15]:
s1 = data.groupby(['Name'])
s2 = s1.get_group('Christine Jacoba Aaftink')
s2['Year'].value_counts()

1988    2
1994    2
1992    2
Name: Year, dtype: int64

In [27]:
#ANSWER: 1988-2 and 1994-2 and 1992-2

__4. Is it true that China won fewer medals than Russia at the 2012 Olympics? Do not consider NaN values in Medal column.__

In [29]:
rf = data.groupby(['Team'])
rf2 = rf.get_group("Russia")
rf2['Medal'].value_counts()

Bronze    393
Gold      366
Silver    351
Name: Medal, dtype: int64

In [30]:
393+366+351

1110

In [31]:
rf3 = rf.get_group("China")
rf3['Medal'].value_counts()

Silver    325
Gold      308
Bronze    268
Name: Medal, dtype: int64

In [32]:
325+308+268

901

In [33]:
#ANSWER: China-901 < Russia-1110

__5. What is the absolute difference between the number of unique sports at the 1986 Olympics and 2016 Olympics?__

In [5]:
ddf = data.groupby(['Year'])
ddf.get_group(1986)

KeyError: 1986

In [6]:
ddf2 = data.groupby(['Year'])
ddf2.get_group(2016)

ID                           Name Sex   Age  Height  Weight  \
80          22                  Andreea Aanei   F  22.0   170.0   125.0   
139         51              Nstor Abad Sanjun   M  23.0   167.0    64.0   
140         51              Nstor Abad Sanjun   M  23.0   167.0    64.0   
141         51              Nstor Abad Sanjun   M  23.0   167.0    64.0   
142         51              Nstor Abad Sanjun   M  23.0   167.0    64.0   
...        ...                            ...  ..   ...     ...     ...   
271024  135528                  Marc Zwiebler   M  32.0   181.0    75.0   
271053  135547  Viktoriya Viktorovna Zyabkina   F  23.0   174.0    62.0   
271054  135547  Viktoriya Viktorovna Zyabkina   F  23.0   174.0    62.0   
271055  135547  Viktoriya Viktorovna Zyabkina   F  23.0   174.0    62.0   
271110  135568         Olga Igorevna Zyuzkova   F  33.0   171.0    69.0   

              Team  NOC        Games  Year  Season            City  \
80         Romania  ROU  2016 Summer  2016  Summer  Rio de Janeiro   
139          Spain  ESP  2016 Summer  2016  Summer  Rio de Janeiro   
140          Spain  ESP  2016 Summer  2016  Summer  Rio de Janeiro   
141          Spain  ESP  2016 Summer  2016  Summer  Rio de Janeiro   
142          Spain  ESP  2016 Summer  2016  Summer  Rio de Janeiro   
...            ...  ...          ...   ...     ...             ...   
271024     Germany  GER  2016 Summer  2016  Summer  Rio de Janeiro   
271053  Kazakhstan  KAZ  2016 Summer  2016  Summer  Rio de Janeiro   
271054  Kazakhstan  KAZ  2016 Summer  2016  Summer  Rio de Janeiro   
271055  Kazakhstan  KAZ  2016 Summer  2016  Summer  Rio de Janeiro   
271110     Belarus  BLR  2016 Summer  2016  Summer  Rio de Janeiro   

                Sport                                    Event Medal  
80      Weightlifting  Weightlifting Women's Super-Heavyweight   NaN  
139        Gymnastics   Gymnastics Men's Individual All-Around   NaN  
140        Gymnastics          Gymnastics Men's Floor Exercise   NaN  
141        Gymnastics           Gymnastics Men's Parallel Bars   NaN  
142        Gymnastics          Gymnastics Men's Horizontal Bar   NaN  
...               ...                                      ...   ...  
271024      Badminton                  Badminton Men's Singles   NaN  
271053      Athletics             Athletics Women's 100 metres   NaN  
271054      Athletics             Athletics Women's 200 metres   NaN  
271055      Athletics   Athletics Women's 4 x 100 metres Relay   NaN  
271110     Basketball            Basketball Women's Basketball   NaN  

[13688 rows x 15 columns]

# Part 2

**In part 2 you need to work with numpy library. Write code and perform computations in the cells below. There are five questions.** 

In [16]:
import numpy as np

__6. Create a 5x5 matrix with row values ranging from 0 to 4__

In [17]:
arr1 = np.zeros((5,5))
arr1 += np.arange(5)
arr1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

__7. Create a random vector of size 10 and sort it__

In [6]:
arr2 = np.random.randn(10)
arr2.sort()
arr2

array([-1.3368572 , -0.8715282 , -0.49422448, -0.29121159,  0.20938792,
        0.39083912,  1.25348259,  1.32506802,  1.43688479,  1.69776893])

__8. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area__

In [4]:
arr3 = np.zeros((10, 10), [('x',float),('y',float)])
arr3['x'], arr3['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(arr3)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

__9. Consider two random array A and B, check if they are equal__

In [7]:
arr4 = np.random.randint(0,2,10)
print(arr4)
arr5 = np.random.randint(0,2,10)
print(arr5)
arr4 == arr5

[1 1 1 1 0 0 1 0 0 1]
[0 0 1 1 0 0 0 1 1 0]


array([False, False,  True,  True,  True,  True, False, False, False,
       False])

__10. Create a random matrix and swap two rows of an array?__

In [8]:
arr6 = np.random.randint(10, size=(5,5))
print(arr6)
arr6[[2, 4]] = arr6[[4,2]]
arr6

[[2 6 3 2 8]
 [8 9 6 3 3]
 [9 7 7 7 4]
 [7 9 5 7 3]
 [9 5 2 7 2]]


array([[2, 6, 3, 2, 8],
       [8, 9, 6, 3, 3],
       [9, 5, 2, 7, 2],
       [7, 9, 5, 7, 3],
       [9, 7, 7, 7, 4]])